#!/usr/bin/env python3
"""
Bundles the site into one self-contained wave-guesser.html.

Every stylesheet and script referenced by index.html is inlined, so the result
is a single file that can be downloaded and opened straight from disk — no
server, no install. Browsers allow a file:// page to call the Wikimedia APIs
because those respond with `Access-Control-Allow-Origin: *`, so the photos
still load.

Usage:  python3 tools/build-single-file.py
"""

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE = ROOT / "index.html"
OUTPUT = ROOT / "wave-guesser.html"

LINK = re.compile(r'[ \t]*<link rel="stylesheet" href="([^"]+)">\n?')
SCRIPT = re.compile(r'[ \t]*<script src="([^"]+)"></script>\n?')


def read(rel_path):
    path = ROOT / rel_path
    if not path.is_file():
        sys.exit("missing asset referenced by index.html: " + rel_path)
    return path.read_text(encoding="utf-8")


def guard(text, closing_tag, rel_path):
    """An asset containing its own closing tag would end the block early."""
    if closing_tag in text.lower():
        sys.exit("cannot inline " + rel_path + ": it contains " + closing_tag)
    return text


def main():
    html = SOURCE.read_text(encoding="utf-8")
    inlined = []

    def css(match):
        rel = match.group(1)
        inlined.append(rel)
        return "<style>\n" + guard(read(rel), "</style", rel) + "\n</style>\n"

    def js(match):
        rel = match.group(1)
        inlined.append(rel)
        return "<script>\n" + guard(read(rel), "</script", rel) + "\n</script>\n"

    # Check the markup for other local references BEFORE inlining, so that
    # href strings built at runtime inside the scripts aren't mistaken for them.
    markup_only = SCRIPT.sub("", LINK.sub("", html))
    leftovers = re.findall(r'(?:href|src)="((?!https?:|data:|#)[^"]+)"', markup_only)
    if leftovers:
        sys.exit("these local references would break in a single file: " + ", ".join(leftovers))

    html = LINK.sub(css, html)
    html = SCRIPT.sub(js, html)

    banner = (
        "<!--\n"
        "  Wave Guesser - single-file build. Generated by tools/build-single-file.py;\n"
        "  edit the sources in assets/ and rebuild rather than editing this file.\n"
        "  Open it in any browser. An internet connection is needed for the beach\n"
        "  photos (Wikimedia) and the map tiles (OpenStreetMap via CARTO).\n"
        "-->\n"
    )
    OUTPUT.write_text(banner + html, encoding="utf-8")

    print("inlined:")
    for rel in inlined:
        print("  " + rel)
    print("wrote " + OUTPUT.name + " (" + format(OUTPUT.stat().st_size / 1024, ".0f") + " KB)")


if __name__ == "__main__":
    main()
